### ISSUE TITLE
Issue build apk

### ISSUE THREAD

**Issue by sornbarang** [creativetimofficial/material-kit-react-native#10]
Request failed with status code 400
Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by palingheorghe** [comment]
Hi @sornbarang ! 

Thank you for being interested in our products! Could you please give us more information regarding this issue? Like the `expo-cli` package version and the `package.json`? As far as I can see this problem has something to do with `axios` which is a library we haven't installed in our products. 

Thanks,
Alin
